# Generated by Django 4.2.16 on 2026-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
